spring:
  config:
    activate:
      on-profile: common

  redis:
    host: localhost
    port: 6379

  jwt:
    # 글자가 짧으면 WeakKeyException 에러가 발생한다. 32글자 이상이어야 한다.
    # 추후에 환경 변수로 넣어야 한다.
    secret: ${JWT_SECRET}

# springdoc swagger
springdoc:
  # 클라이언트가 서버에게 보내는 데이터 타입
  default-consumes-media-type: application/json
  # 서버가 클라이언트에게 반환하는 데이터 타입
  default-produces-media-type: application/json
  api-docs:
    # JSON 제공 접속 path 설정
    path: /swagger/docs

  swagger-ui:
    # UI 제공 접속 path 설정
    path: /swagger/ui
    # Try it out 시 Request Duration 표시
    display-request-duration: true

  cache:
    # 캐시 비활성화 (로컬에서만 사용 권장)
    disabled: true

  # @ControllerAdvice 응답이 API 응답에 포함 (기본값 true). 필자는 ErrorHandler 에서 사용했다.
  override-with-generic-response: true

