spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc:mysql://[데이터베이스 서비스 명]:[데이터베이스 포트]/[데이터베이스 명]
    url: jdbc:mysql://db_mysql:3306/${MYSQL_DATABASE}
    # 데이터베이스에 접속할 사용자와 비밀번호
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      # 실제 운영할 때는 validate 나 none 으로 설정해야 한다. DB가 날아갈 수 있다.
      # 다만 처음에 시작할 때는 create나 update로 테이블을 생성해주어야 한다.
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500

  redis:
    host: cache_redis
    port: 6379
    password: ${REDIS_PASSWORD}

logging.level:
  # logger 를 통해 하이버네이트 실행 SQL을 남긴다. INFO, WARN, ERROR 만 남기도록 설정한다.
  org.hibernate.SQL: debug

# 배포 환경에서는 리소스 소모가 심하므로 p6spy 로깅을 OFF 해준다.
decorator:
  datasource:
    p6spy:
      enable-logging: false